<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title> 6 Dados qualitativos: mapa corocromático nominal | Cartografia Temática em R para estudantes de Geografia</title>
  <meta name="description" content=" 6 Dados qualitativos: mapa corocromático nominal | Cartografia Temática em R para estudantes de Geografia" />
  <meta name="generator" content="bookdown 0.34 and GitBook 2.6.7" />

  <meta property="og:title" content=" 6 Dados qualitativos: mapa corocromático nominal | Cartografia Temática em R para estudantes de Geografia" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content=" 6 Dados qualitativos: mapa corocromático nominal | Cartografia Temática em R para estudantes de Geografia" />
  
  
  

<meta name="author" content="Ligia Vizeu Barrozo" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="tipos.html"/>
<link rel="next" href="quali2.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">R Carto Tem Geo</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Apresentação</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#referência-citada"><i class="fa fa-check"></i>Referência citada</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="sobre-o-livro.html"><a href="sobre-o-livro.html"><i class="fa fa-check"></i>Sobre o livro</a></li>
<li class="chapter" data-level="" data-path="agradecimentos.html"><a href="agradecimentos.html"><i class="fa fa-check"></i>Agradecimentos</a></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introdução</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#o-programa-r"><i class="fa fa-check"></i><b>1.1</b> O programa R</a></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#instalação-do-r-e-rstudio"><i class="fa fa-check"></i><b>1.2</b> Instalação do R e RStudio</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="intro.html"><a href="intro.html#instalação-do-r-para-windows"><i class="fa fa-check"></i><b>1.2.1</b> Instalação do R para Windows</a></li>
<li class="chapter" data-level="1.2.2" data-path="intro.html"><a href="intro.html#instalação-do-r-para-mac"><i class="fa fa-check"></i><b>1.2.2</b> Instalação do R para Mac</a></li>
<li class="chapter" data-level="1.2.3" data-path="intro.html"><a href="intro.html#instalação-do-rstudio"><i class="fa fa-check"></i><b>1.2.3</b> Instalação do RStudio</a></li>
<li class="chapter" data-level="1.2.4" data-path="intro.html"><a href="intro.html#instalação-do-rtools"><i class="fa fa-check"></i><b>1.2.4</b> Instalação do RTools</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="basico.html"><a href="basico.html"><i class="fa fa-check"></i><b>2</b> Básico do básico do R e RStudio</a>
<ul>
<li class="chapter" data-level="2.1" data-path="basico.html"><a href="basico.html#os-paineis"><i class="fa fa-check"></i><b>2.1</b> Os paineis</a></li>
<li class="chapter" data-level="2.2" data-path="basico.html"><a href="basico.html#tipos-de-objetos"><i class="fa fa-check"></i><b>2.2</b> Tipos de objetos</a></li>
<li class="chapter" data-level="2.3" data-path="basico.html"><a href="basico.html#estrutura-dos-dados"><i class="fa fa-check"></i><b>2.3</b> Estrutura dos dados</a></li>
<li class="chapter" data-level="2.4" data-path="basico.html"><a href="basico.html#vetores"><i class="fa fa-check"></i><b>2.4</b> Vetores</a></li>
<li class="chapter" data-level="2.5" data-path="basico.html"><a href="basico.html#nomeando-os-vetores"><i class="fa fa-check"></i><b>2.5</b> Nomeando os vetores</a></li>
<li class="chapter" data-level="2.6" data-path="basico.html"><a href="basico.html#seleção-em-vetores"><i class="fa fa-check"></i><b>2.6</b> Seleção em vetores</a></li>
<li class="chapter" data-level="2.7" data-path="basico.html"><a href="basico.html#totais-e-médias-em-vetores"><i class="fa fa-check"></i><b>2.7</b> Totais e médias em vetores</a></li>
<li class="chapter" data-level="2.8" data-path="basico.html"><a href="basico.html#matrizes"><i class="fa fa-check"></i><b>2.8</b> Matrizes</a></li>
<li class="chapter" data-level="2.9" data-path="basico.html"><a href="basico.html#cálculos-em-matrizes"><i class="fa fa-check"></i><b>2.9</b> Cálculos em Matrizes</a></li>
<li class="chapter" data-level="2.10" data-path="basico.html"><a href="basico.html#seleção-em-matrizes"><i class="fa fa-check"></i><b>2.10</b> Seleção em Matrizes</a></li>
<li class="chapter" data-level="2.11" data-path="basico.html"><a href="basico.html#fatores"><i class="fa fa-check"></i><b>2.11</b> Fatores</a></li>
<li class="chapter" data-level="2.12" data-path="basico.html"><a href="basico.html#referências-citadas"><i class="fa fa-check"></i><b>2.12</b> Referências citadas</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="dataframes.html"><a href="dataframes.html"><i class="fa fa-check"></i><b>3</b> Dataframes</a>
<ul>
<li class="chapter" data-level="3.1" data-path="dataframes.html"><a href="dataframes.html#criação-de-dataframe"><i class="fa fa-check"></i><b>3.1</b> Criação de dataframe</a></li>
<li class="chapter" data-level="3.2" data-path="dataframes.html"><a href="dataframes.html#importação-de-um-dataframe"><i class="fa fa-check"></i><b>3.2</b> Importação de um dataframe</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="tidyverse.html"><a href="tidyverse.html"><i class="fa fa-check"></i><b>4</b> Básico do Tidyverse</a>
<ul>
<li class="chapter" data-level="4.1" data-path="tidyverse.html"><a href="tidyverse.html#o-operador-pipe-no-tidyverse"><i class="fa fa-check"></i><b>4.1</b> O operador Pipe no tidyverse</a></li>
<li class="chapter" data-level="4.2" data-path="tidyverse.html"><a href="tidyverse.html#selecionando-colunas"><i class="fa fa-check"></i><b>4.2</b> Selecionando colunas</a></li>
<li class="chapter" data-level="4.3" data-path="tidyverse.html"><a href="tidyverse.html#combinando-dataframes"><i class="fa fa-check"></i><b>4.3</b> Combinando dataframes</a></li>
<li class="chapter" data-level="4.4" data-path="tidyverse.html"><a href="tidyverse.html#filtrando-observações"><i class="fa fa-check"></i><b>4.4</b> Filtrando observações</a></li>
<li class="chapter" data-level="4.5" data-path="tidyverse.html"><a href="tidyverse.html#organizando-uma-tabela-com-a-função-arrange"><i class="fa fa-check"></i><b>4.5</b> Organizando uma tabela com a função <code>arrange()</code></a></li>
<li class="chapter" data-level="4.6" data-path="tidyverse.html"><a href="tidyverse.html#o-verbo-mutate"><i class="fa fa-check"></i><b>4.6</b> O verbo “mutate”</a></li>
<li class="chapter" data-level="4.7" data-path="tidyverse.html"><a href="tidyverse.html#agrupando-dados-com-a-função-group_by"><i class="fa fa-check"></i><b>4.7</b> Agrupando dados com a função <code>group_by</code></a></li>
<li class="chapter" data-level="4.8" data-path="tidyverse.html"><a href="tidyverse.html#rumo-aos-mapas"><i class="fa fa-check"></i><b>4.8</b> Rumo aos mapas</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="tipos.html"><a href="tipos.html"><i class="fa fa-check"></i><b>5</b> Tipos de dados, conceitos e representação cartográfica</a>
<ul>
<li class="chapter" data-level="5.1" data-path="tipos.html"><a href="tipos.html#definição-do-tipo-de-representação-cartográfica"><i class="fa fa-check"></i><b>5.1</b> Definição do tipo de representação cartográfica</a></li>
<li class="chapter" data-level="5.2" data-path="tipos.html"><a href="tipos.html#variáveis-visuais"><i class="fa fa-check"></i><b>5.2</b> Variáveis visuais</a></li>
<li class="chapter" data-level="5.3" data-path="tipos.html"><a href="tipos.html#o-conceito-diversidade"><i class="fa fa-check"></i><b>5.3</b> O conceito <em>diversidade</em></a></li>
<li class="chapter" data-level="5.4" data-path="tipos.html"><a href="tipos.html#o-conceito-ordem"><i class="fa fa-check"></i><b>5.4</b> O conceito <em>ordem</em></a></li>
<li class="chapter" data-level="5.5" data-path="tipos.html"><a href="tipos.html#o-conceito-de-proporcionalidade"><i class="fa fa-check"></i><b>5.5</b> O conceito de <em>proporcionalidade</em></a></li>
<li class="chapter" data-level="5.6" data-path="tipos.html"><a href="tipos.html#referências-sugeridas"><i class="fa fa-check"></i><b>5.6</b> Referências sugeridas</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="quali1.html"><a href="quali1.html"><i class="fa fa-check"></i><b>6</b> Dados qualitativos: mapa corocromático nominal</a>
<ul>
<li class="chapter" data-level="6.1" data-path="quali1.html"><a href="quali1.html#instalando-e-carregando-pacotes-do-r"><i class="fa fa-check"></i><b>6.1</b> Instalando e carregando pacotes do R</a></li>
<li class="chapter" data-level="6.2" data-path="quali1.html"><a href="quali1.html#o-pacote-geobr"><i class="fa fa-check"></i><b>6.2</b> O pacote geobr</a></li>
<li class="chapter" data-level="6.3" data-path="quali1.html"><a href="quali1.html#projeção-cartográfica"><i class="fa fa-check"></i><b>6.3</b> Projeção cartográfica</a></li>
<li class="chapter" data-level="6.4" data-path="quali1.html"><a href="quali1.html#iniciando-com-o-ggplot2"><i class="fa fa-check"></i><b>6.4</b> Iniciando com o ggplot2</a></li>
<li class="chapter" data-level="6.5" data-path="quali1.html"><a href="quali1.html#biomas-do-brasil"><i class="fa fa-check"></i><b>6.5</b> Biomas do Brasil</a></li>
<li class="chapter" data-level="" data-path="quali1.html"><a href="quali1.html#referências-citadas-1"><i class="fa fa-check"></i>Referências citadas</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="quali2.html"><a href="quali2.html"><i class="fa fa-check"></i><b>7</b> Dados qualitativos: mapa corocromático ordinal</a>
<ul>
<li class="chapter" data-level="7.1" data-path="quali2.html"><a href="quali2.html#banco-de-dados"><i class="fa fa-check"></i><b>7.1</b> Banco de dados</a></li>
<li class="chapter" data-level="7.2" data-path="quali2.html"><a href="quali2.html#potencial-de-agressividade-climática-na-amazônia-legal-do-brasil"><i class="fa fa-check"></i><b>7.2</b> Potencial de agressividade climática na Amazônia Legal do Brasil</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="quanti1.html"><a href="quanti1.html"><i class="fa fa-check"></i><b>8</b> Dados quantitativos absolutos: mapa das figuras geométricas proporcionais</a>
<ul>
<li class="chapter" data-level="8.1" data-path="quanti1.html"><a href="quanti1.html#bases-de-dados"><i class="fa fa-check"></i><b>8.1</b> Bases de dados</a></li>
<li class="chapter" data-level="8.2" data-path="quanti1.html"><a href="quanti1.html#centroides-dos-municípios"><i class="fa fa-check"></i><b>8.2</b> Centroides dos municípios</a></li>
<li class="chapter" data-level="8.3" data-path="quanti1.html"><a href="quanti1.html#mapa-da-população-do-estado-de-são-paulo"><i class="fa fa-check"></i><b>8.3</b> Mapa da população do estado de São Paulo</a></li>
<li class="chapter" data-level="8.4" data-path="quanti1.html"><a href="quanti1.html#referências-sugeridas-1"><i class="fa fa-check"></i><b>8.4</b> Referências sugeridas</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="quanti2.html"><a href="quanti2.html"><i class="fa fa-check"></i><b>9</b> Dados quantitativos absolutos: mapa dos pontos de contagem (ou densidade de pontos)</a>
<ul>
<li class="chapter" data-level="9.1" data-path="quanti2.html"><a href="quanti2.html#bases-de-dados-1"><i class="fa fa-check"></i><b>9.1</b> Bases de dados</a></li>
<li class="chapter" data-level="9.2" data-path="quanti2.html"><a href="quanti2.html#definição-dos-pontos-aleatórios"><i class="fa fa-check"></i><b>9.2</b> Definição dos pontos aleatórios</a></li>
<li class="chapter" data-level="9.3" data-path="quanti2.html"><a href="quanti2.html#mapa-de-raça-ou-cor-dos-residentes-do-município-de-são-paulo"><i class="fa fa-check"></i><b>9.3</b> Mapa de raça ou cor dos residentes do município de São Paulo</a></li>
<li class="chapter" data-level="9.4" data-path="quanti2.html"><a href="quanti2.html#referências-sugeridas-2"><i class="fa fa-check"></i><b>9.4</b> Referências sugeridas</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="quanti3.html"><a href="quanti3.html"><i class="fa fa-check"></i><b>10</b> Dados quantitativos relativos: mapa coroplético</a>
<ul>
<li class="chapter" data-level="10.1" data-path="quanti3.html"><a href="quanti3.html#bancos-de-dados"><i class="fa fa-check"></i><b>10.1</b> Bancos de dados</a></li>
<li class="chapter" data-level="10.2" data-path="quanti3.html"><a href="quanti3.html#mapas-coropléticos"><i class="fa fa-check"></i><b>10.2</b> Mapas coropléticos</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="quanti3.html"><a href="quanti3.html#o-número-de-classes"><i class="fa fa-check"></i><b>10.2.1</b> O número de classes</a></li>
<li class="chapter" data-level="10.2.2" data-path="quanti3.html"><a href="quanti3.html#histogramas-das-variáveis"><i class="fa fa-check"></i><b>10.2.2</b> Histogramas das variáveis</a></li>
<li class="chapter" data-level="10.2.3" data-path="quanti3.html"><a href="quanti3.html#os-intervalos-de-classes"><i class="fa fa-check"></i><b>10.2.3</b> Os intervalos de classes</a></li>
<li class="chapter" data-level="10.2.4" data-path="quanti3.html"><a href="quanti3.html#escalacores"><i class="fa fa-check"></i><b>10.2.4</b> A escala de cores</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="quanti3.html"><a href="quanti3.html#layout-do-mapa-coroplético-de-idhm-da-rmsp"><i class="fa fa-check"></i><b>10.3</b> Layout do mapa coroplético de IDHM da RMSP</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="quanti4.html"><a href="quanti4.html"><i class="fa fa-check"></i><b>11</b> Mapa coroplético interativo</a>
<ul>
<li class="chapter" data-level="11.1" data-path="quanti4.html"><a href="quanti4.html#indo-além-proposta-de-exercício"><i class="fa fa-check"></i><b>11.1</b> Indo além: Proposta de exercício</a></li>
<li class="chapter" data-level="11.2" data-path="quanti4.html"><a href="quanti4.html#referências-sugeridas-3"><i class="fa fa-check"></i><b>11.2</b> Referências sugeridas</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="quanti5.html"><a href="quanti5.html"><i class="fa fa-check"></i><b>12</b> Dados quantitativos a partir de amostras: mapa isarítmico</a>
<ul>
<li class="chapter" data-level="12.1" data-path="quanti5.html"><a href="quanti5.html#referências-sugeridas-4"><i class="fa fa-check"></i><b>12.1</b> Referências sugeridas</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="quanti6.html"><a href="quanti6.html"><i class="fa fa-check"></i><b>13</b> Mapa de fluxos: movimentos no espaço</a></li>
<li class="chapter" data-level="14" data-path="osm.html"><a href="osm.html"><i class="fa fa-check"></i><b>14</b> Usando dados do Open Street Map</a></li>
<li class="chapter" data-level="15" data-path="anamorf.html"><a href="anamorf.html"><i class="fa fa-check"></i><b>15</b> Anamorfose</a></li>
<li class="chapter" data-level="16" data-path="sintese.html"><a href="sintese.html"><i class="fa fa-check"></i><b>16</b> Mapas de síntese</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Cartografia Temática em R para estudantes de Geografia</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="quali1" class="section level1 hasAnchor" number="6">
<h1><span class="header-section-number"> 6</span> Dados qualitativos: mapa corocromático nominal<a href="quali1.html#quali1" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="instalando-e-carregando-pacotes-do-r" class="section level2 hasAnchor" number="6.1">
<h2><span class="header-section-number">6.1</span> Instalando e carregando pacotes do R<a href="quali1.html#instalando-e-carregando-pacotes-do-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Inicie o <strong>RStudio</strong>, no Menu <em>File</em>, escolha <em>New File</em> e <em>R Script</em>.</p>
<p>Embora, na primeira vez de acesso não seja necessário limpar a memória, das outras vezes, ao iniciar o <strong>RStudio</strong>, é recomendável sempre limpá-la e definir o diretório de trabalho. Digite o seguinte comando:</p>
<div class="sourceCode" id="cb195"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb195-1"><a href="quali1.html#cb195-1" tabindex="-1"></a><span class="co">#para limpar a memória</span></span>
<span id="cb195-2"><a href="quali1.html#cb195-2" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list=</span><span class="fu">ls</span>(<span class="at">all=</span><span class="cn">TRUE</span>))</span></code></pre></div>
<p>O que estiver depois do sinal # são anotações sobre o caminho percorrido que podem ajudar na memorização e não interferem no código. Você pode escrever o que quiser como anotação.</p>
<p>Para definir o diretório de trabalho, use a função <em>setwd</em> (de <em>set working diretory</em>, ou defina o diretório de trabalho, em português). Entre parênteses o caminho do diretório deve estar entre aspas e com a barra nesta direção /. Para verificar o diretório definido, use <code>getwd()</code>:</p>
<div class="sourceCode" id="cb196"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb196-1"><a href="quali1.html#cb196-1" tabindex="-1"></a><span class="co">#para definir o diretório de trabalho</span></span>
<span id="cb196-2"><a href="quali1.html#cb196-2" tabindex="-1"></a><span class="fu">getwd</span>()</span></code></pre></div>
<p>Além do <strong>R</strong> e <strong>RStudio</strong>, usaremos uma série de outros pacotes do <strong>R</strong> que podem ser instalados de uma vez, usando a função <strong>install.packages</strong> (instalar pacotes):</p>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb197-1"><a href="quali1.html#cb197-1" tabindex="-1"></a><span class="co">#para instalar os pacotes</span></span>
<span id="cb197-2"><a href="quali1.html#cb197-2" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="fu">c</span>(</span>
<span id="cb197-3"><a href="quali1.html#cb197-3" tabindex="-1"></a>  <span class="st">&quot;devtools&quot;</span>, <span class="st">&quot;dplyr&quot;</span>, <span class="st">&quot;ggplot2&quot;</span>, <span class="st">&quot;ggtext&quot;</span>, <span class="st">&quot;ggthemes&quot;</span>, <span class="st">&quot;rgdal&quot;</span>,<span class="st">&quot;rnaturalearth&quot;</span>, <span class="st">&quot;rnaturalearthdata&quot;</span>, <span class="st">&quot;sf&quot;</span>, <span class="st">&quot;sp&quot;</span>,<span class="st">&quot;tidyr&quot;</span> </span>
<span id="cb197-4"><a href="quali1.html#cb197-4" tabindex="-1"></a>))</span></code></pre></div>
<p>Os pacotes <strong>rnaturalearth</strong> e <strong>rnaturalearthdata</strong> facilitam a elaboração de mapas em <strong>R</strong> com dados de feições naturais da Terra que se encontram em <a href="http://www.naturalearthdata.com/" class="uri">http://www.naturalearthdata.com/</a>.</p>
<p>Vamos carregar alguns dos pacotes para a elaboração do mapa corocromático nominal, usando a função <strong>library</strong> para carregar as bibliotecas (pacotes instalados):</p>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb198-1"><a href="quali1.html#cb198-1" tabindex="-1"></a><span class="co">#para carregar os pacotes</span></span>
<span id="cb198-2"><a href="quali1.html#cb198-2" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb198-3"><a href="quali1.html#cb198-3" tabindex="-1"></a><span class="fu">library</span>(devtools)</span>
<span id="cb198-4"><a href="quali1.html#cb198-4" tabindex="-1"></a><span class="fu">library</span>(rgdal)</span>
<span id="cb198-5"><a href="quali1.html#cb198-5" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb198-6"><a href="quali1.html#cb198-6" tabindex="-1"></a><span class="fu">library</span>(sp)</span>
<span id="cb198-7"><a href="quali1.html#cb198-7" tabindex="-1"></a><span class="fu">library</span>(rnaturalearth)</span>
<span id="cb198-8"><a href="quali1.html#cb198-8" tabindex="-1"></a><span class="fu">library</span>(rnaturalearthdata)</span></code></pre></div>
</div>
<div id="o-pacote-geobr" class="section level2 hasAnchor" number="6.2">
<h2><span class="header-section-number">6.2</span> O pacote geobr<a href="quali1.html#o-pacote-geobr" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>O pacote <strong>geobr</strong> foi desenvolvido por pesquisadores do Instituto de Pesquisa Econômica Aplicada (IPEA), que é uma fundação pública federal vinculada ao Ministério da Economia do Brasil, para importar os dados do IBGE (PEREIRA &amp; GONÇALVES, 2021). Este pacote está depositado no <em>github</em> do IPEA. Para facilitar a instalação de pacotes que não estão no repositório CRAN, pode-se usar o pacote <strong>devtools</strong> com a função <strong>install_github()</strong>. Se você seguiu os passos anteriores, o <strong>devtools</strong> já está instalado e carregado no <strong>RStudio</strong>.</p>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb199-1"><a href="quali1.html#cb199-1" tabindex="-1"></a><span class="co">#para instalar o pacote ‘geobr’</span></span>
<span id="cb199-2"><a href="quali1.html#cb199-2" tabindex="-1"></a>devtools<span class="sc">::</span><span class="fu">install_github</span>(<span class="st">&quot;ipeaGIT/geobr&quot;</span>, <span class="at">subdir =</span> <span class="st">&quot;r-package&quot;</span>)</span></code></pre></div>
<p>Você deve estar curioso para saber o que significa <strong>::</strong> . O que vem antes de <strong>::</strong> é o nome do pacote a ser utilizado e o que vem depois, a função a ser usada. É muito útil, pois muitas vezes nos esquecemos de carregar um determinado pacote com a função <strong>library()</strong> e, mesmo assim, o <strong>R</strong> identifica o pacote e executa a função. Além disso, como as funções podem ter o mesmo nome em vários pacotes, o <strong>R</strong> utilizará a função cujo pacote foi carregado por último, não necessariamente a que você deseja. Usando <strong>::</strong> deixa claro o pacote cuja função você quer executar.</p>
<p>Vamos carregar o pacote que acabamos de instalar.</p>
<div class="sourceCode" id="cb200"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb200-1"><a href="quali1.html#cb200-1" tabindex="-1"></a><span class="co">#para carregar o pacote</span></span>
<span id="cb200-2"><a href="quali1.html#cb200-2" tabindex="-1"></a><span class="fu">library</span>(geobr)</span></code></pre></div>
<p>O pacote <strong>geobr</strong> contém 27 conjuntos de dados do IBGE para importação. Este pacote evita que você tenha que ir ao site do IBGE para fazer o <em>download</em> individualmente de cada base cartográfica que pretende usar. Uma vez carregado no <strong>RStudio</strong>, você consegue fazer <em>download</em> dos dados segundo diferentes divisões territoriais. Para ter uma ideia do conteúdo do <strong>geobr</strong>, use a função <strong>list_geobr()</strong>, como a seguir:</p>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb201-1"><a href="quali1.html#cb201-1" tabindex="-1"></a><span class="co">#para listar o conteúdo do ‘geobr’</span></span>
<span id="cb201-2"><a href="quali1.html#cb201-2" tabindex="-1"></a><span class="fu">list_geobr</span>()</span></code></pre></div>
<p>Como iremos fazer um mapa dos biomas do Brasil, vamos criar um objeto chamado <strong>biomas</strong>. Este conjunto de dados inclui polígonos de todos os biomas presentes no território brasileiro e zona costeira. O conjunto de dados de 2019 está disponível na escala 1:250.000. Para isso, vamos atribuir o nome ‘biomas’ antes dos sinais <strong>&lt;-</strong> e usar a função <strong>read_biomes</strong> do <strong>geobr</strong>, selecionando o ano dos dados de interesse - 2019. O argumento <em>simplified</em> é um argumento lógico (FALSO ou VERDADEIRO/<em>FALSE or TRUE</em>) que indica se a função deve retornar o conjunto de dados com a resolução original ou com os limites simplificados. A predefinição (<em>default</em>) é <strong>TRUE</strong>. Quando se deseja fazer análises espaciais com os dados, a versão com os limites simplificados é indicada. O argumento <em>showProgress</em> indica se deve apresentar a barra de progresso do <em>download</em> (<em>TRUE</em>) ou não (<em>FALSE</em>).</p>
<div class="sourceCode" id="cb202"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb202-1"><a href="quali1.html#cb202-1" tabindex="-1"></a><span class="co">#para criar um objeto chamado ‘biomas’ a partir do conjunto de dados do IBGE</span></span>
<span id="cb202-2"><a href="quali1.html#cb202-2" tabindex="-1"></a>biomas <span class="ot">&lt;-</span> <span class="fu">read_biomes</span>(<span class="at">year =</span> <span class="dv">2019</span>, <span class="at">simplified =</span> <span class="cn">TRUE</span>, <span class="at">showProgress =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## Using year 2019</code></pre>
<p>Confira o tipo de objeto gerado:</p>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb204-1"><a href="quali1.html#cb204-1" tabindex="-1"></a><span class="co">#para ver o tipo de objeto</span></span>
<span id="cb204-2"><a href="quali1.html#cb204-2" tabindex="-1"></a><span class="fu">class</span>(biomas)</span></code></pre></div>
<pre><code>## [1] &quot;sf&quot;         &quot;data.frame&quot;</code></pre>
<p>Observe que a palavra ‘biomas’ aparece como um objeto no painel ‘Environment’ do <strong>RStudio</strong>. É um objeto do tipo ‘sf’ (espacial) e ‘data.frame’ porque tem uma tabela de dados alfa-numérica associada.</p>
<div class="sourceCode" id="cb206"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb206-1"><a href="quali1.html#cb206-1" tabindex="-1"></a><span class="co">#para ver a tabela de dados de ‘biomas’</span></span>
<span id="cb206-2"><a href="quali1.html#cb206-2" tabindex="-1"></a><span class="fu">View</span>(biomas)</span></code></pre></div>
<p>Pode ser que demore um pouco para abrir. Você verá uma tabela que contém as seguintes colunas: <strong>name_biome</strong>, <strong>code_biome</strong>, <strong>year</strong>, <strong>geom</strong>. A tabela de dados possui uma coluna para os nomes dos biomas, outra para os códigos atribuídos a cada bioma, outra com o ano dos dados e a última com a geometria (coordenadas de cada vértice para todos os polígonos). Se você quiser ver apenas os nomes das variáveis (colunas), digite a função <strong>names()</strong>.</p>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb207-1"><a href="quali1.html#cb207-1" tabindex="-1"></a><span class="co">#para ver os nomes das colunas do objeto ‘biomas’</span></span>
<span id="cb207-2"><a href="quali1.html#cb207-2" tabindex="-1"></a><span class="fu">names</span>(biomas)</span></code></pre></div>
<pre><code>## [1] &quot;name_biome&quot; &quot;code_biome&quot; &quot;year&quot;       &quot;geom&quot;</code></pre>
<p>Usando apenas o comando básico do <strong>R</strong>, conseguimos visualizar os dados espaciais. Vamos usar a função <strong>plot()</strong> para isso. O que temos é a Figura <a href="quali1.html#fig:plot-biom">6.1</a>. Observamos que a partir da geometria (geom) foi elaborado um mapa para cada coluna da tabela de dados.</p>
<div class="sourceCode" id="cb209"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb209-1"><a href="quali1.html#cb209-1" tabindex="-1"></a><span class="co">#para visualizar o objeto ‘biomas’</span></span>
<span id="cb209-2"><a href="quali1.html#cb209-2" tabindex="-1"></a><span class="fu">plot</span>(biomas)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:plot-biom"></span>
<img src="bookdownproj_files/figure-html/plot-biom-1.png" alt="Mapa para cada coluna da tabela de dados" width="672" />
<p class="caption">
Figure 6.1: Mapa para cada coluna da tabela de dados
</p>
</div>
</div>
<div id="projeção-cartográfica" class="section level2 hasAnchor" number="6.3">
<h2><span class="header-section-number">6.3</span> Projeção cartográfica<a href="quali1.html#projeção-cartográfica" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Quando elaboramos um mapa, é sempre interessante colocarmos a área mapeada em um contexto mais amplo. Isso pode ser feito no próprio mapa ou inserindo um mapa de referência dentro da área de plotagem. Vamos fazer a primeira opção.</p>
<p>Quando adicionamos mais de uma camada em um mapa, precisamos ficar atentos às projeções cartográficas das duas camadas. Vamos conferir a projeção da camada <strong>biomas</strong>.</p>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb210-1"><a href="quali1.html#cb210-1" tabindex="-1"></a><span class="fu">head</span>(biomas)</span></code></pre></div>
<pre><code>## Simple feature collection with 6 features and 3 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: -73.98304 ymin: -33.75115 xmax: -28.84785 ymax: 5.269581
## Geodetic CRS:  SIRGAS 2000
##       name_biome code_biome year                           geom
## 1       Amazônia          1 2019 MULTIPOLYGON (((-44.08515 -...
## 2       Caatinga          2 2019 MULTIPOLYGON (((-41.7408 -2...
## 3        Cerrado          3 2019 MULTIPOLYGON (((-43.39009 -...
## 4 Mata Atlântica          4 2019 MULTIPOLYGON (((-48.70814 -...
## 5          Pampa          5 2019 MULTIPOLYGON (((-52.82472 -...
## 6       Pantanal          6 2019 MULTIPOLYGON (((-57.75946 -...</code></pre>
<p>Observamos que o sistema de coordenadas de referência <strong>CRS (coordinate reference system)</strong> é SIRGAS 2000.</p>
<p>Vamos criar uma camada do tipo <strong>sf</strong> (<em>simple features</em>) chamada <strong>mundo</strong> a partir do pacote <strong>rnaturalearth</strong>. A função <strong>ne_countries</strong> permite selecionar polígonos, pontos ou <em>sf</em> dos países do mundo em uma escala determinada ou pontos dos países muito pequenos. Para entender melhor, digite <strong>ne_countries</strong> na busca da aba <em>Help</em> do <strong>RStudio</strong>.</p>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb212-1"><a href="quali1.html#cb212-1" tabindex="-1"></a><span class="co">#para criar o objeto &#39;mundo&#39;</span></span>
<span id="cb212-2"><a href="quali1.html#cb212-2" tabindex="-1"></a>mundo <span class="ot">&lt;-</span> <span class="fu">ne_countries</span>(<span class="at">scale =</span> <span class="st">&quot;medium&quot;</span>, <span class="at">returnclass =</span> <span class="st">&quot;sf&quot;</span>)</span>
<span id="cb212-3"><a href="quali1.html#cb212-3" tabindex="-1"></a><span class="co">#para ver o tipo de objetos</span></span>
<span id="cb212-4"><a href="quali1.html#cb212-4" tabindex="-1"></a><span class="fu">class</span>(mundo)</span></code></pre></div>
<pre><code>## [1] &quot;sf&quot;         &quot;data.frame&quot;</code></pre>
<p><strong>mundo</strong> tem duas classes de objetos: um do tipo <strong>sf</strong> (<em>simple feature</em>) e outro do tipo <strong>data.frame</strong> (tabela de dados).
Vamos ver também o <strong>CRS (coordinate reference system)</strong> de <strong>mundo</strong>.</p>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb214-1"><a href="quali1.html#cb214-1" tabindex="-1"></a>sf<span class="sc">::</span><span class="fu">st_crs</span>(mundo)</span></code></pre></div>
<p>O sistema de coordenadas de <strong>mundo</strong> é <strong>+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0</strong>.</p>
<p>Vamos colocar <strong>biomas</strong> na mesma projeção.
O pacote <strong>sf</strong> (<em>simple features for R</em>) (PEBESMA, 2018) permite a manipulação das bases de dados espaciais. Vamos usá-lo para alterar o CRS da camada <strong>biomas</strong>, usando a função <strong>st_transform</strong>.</p>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb215-1"><a href="quali1.html#cb215-1" tabindex="-1"></a><span class="co">#para alterar o CRS de &#39;biomas&#39;</span></span>
<span id="cb215-2"><a href="quali1.html#cb215-2" tabindex="-1"></a>biomaswgs84<span class="ot">&lt;-</span> <span class="fu">st_transform</span>(biomas, <span class="st">&quot;+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb216-1"><a href="quali1.html#cb216-1" tabindex="-1"></a><span class="co">#para verificar o CRS de &#39;biomaswgs84&#39;</span></span>
<span id="cb216-2"><a href="quali1.html#cb216-2" tabindex="-1"></a><span class="fu">st_crs</span>(biomaswgs84)</span></code></pre></div>
<p>O embasamento teórico sobre as projeções cartográficas e sistemas de coordenadas geográficas é primordial para lidar com dados espaciais.</p>
</div>
<div id="iniciando-com-o-ggplot2" class="section level2 hasAnchor" number="6.4">
<h2><span class="header-section-number">6.4</span> Iniciando com o ggplot2<a href="quali1.html#iniciando-com-o-ggplot2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>ggplot2</strong> é um pacote do <strong>R</strong> para produzir gráficos estatísticos ou dados (e mapas, claro!). Seu enorme potencial é descrito em diversos livros. Para aqueles que pretendem se aprofundar, uma ótima referência é Wickham et al. (2016). Todos os detalhes do pacote podem ser encontrados em <a href="https://ggplot2.tidyverse.org/reference/index.html" class="uri">https://ggplot2.tidyverse.org/reference/index.html</a>.</p>
<p>Ao contrário da maioria dos outros pacotes gráficos, o <strong>ggplot2</strong> possui uma gramática subjacente, com base na teoria da <em>gramática dos gráficos</em> (WILKINSON &amp; WILLS, 2005; WICKHAM, 2010), que permite compor gráficos combinando componentes independentes.</p>
<p>Resumidamente, parte-se da ideia de que todo gráfico ou mapa é composto por um conjunto de dados (que fornecerá a informação a ser representada) e o arranjo (a descrição de como as variáveis dos dados são representadas por meio dos atributos estéticos). O arranjo tem cinco componentes:</p>
<p><strong>layer</strong> - uma camada de elementos geométricos (<strong>geom</strong>), que representa o que se vê, como pontos, linhas, polígonos, etc. e a estatística que resume os dados;</p>
<p><strong>scale</strong> - representa os valores do espaço dos dados no espaço estético. Este componente inclui o uso da cor, forma ou tamanho, além de desenhar a legenda e eixos;</p>
<p><strong>coord</strong> - sistema de coordenadas que descreve como as coordenadas dos dados são representadas no plano do gráfico. Também fornece os eixos e linhas de grade;</p>
<p><strong>facet</strong> - especifica como dividir e mostrar subconjuntos dos dados;</p>
<p><strong>theme</strong> - controla os detalhes do gráfico/mapa, tais como o tamanho da fonte ou cor do fundo. Existe um tema padrão definido no <strong>ggplot2</strong> que pode ser modificado.</p>
<p>O pacote <strong>ggplot2</strong> só permite a elaboração de gráficos ou mapas estáticos. Para mapas interativos, outros pacotes podem ser usados, tais como o <strong>leaflet</strong> ou <strong>tmap</strong>.</p>
<p>Usando <strong>ggplot2</strong> podemos especificar diferentes partes do gráfico e combiná-las usando o operador <strong>+</strong> (WICKHAM et al., 2016).</p>
</div>
<div id="biomas-do-brasil" class="section level2 hasAnchor" number="6.5">
<h2><span class="header-section-number">6.5</span> Biomas do Brasil<a href="quali1.html#biomas-do-brasil" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Vamos usar o <strong>ggplot2</strong> para a elaboração do mapa de Biomas do Brasil. Agora que as camadas já estão com o mesmo CRS, vamos começar a adicioná-las por partes e configurar o mapa. No <strong>ggplot2</strong>, os mapas são construídos adicionando-se camada sobre camada, sendo a primeira delas dada pela função <strong>ggplot()</strong> (sem o número “2”).
Primeiro vamos carregar a camada <strong>mundo</strong>. Digitamos a função <strong>ggplot()</strong>, definimos o banco de dados, no caso, <strong>mundo</strong> e acrescentamos o sinal <strong>+</strong>. <strong>sf</strong> é o acrônimo de <em>simple features</em> e desenha objetos geométricos diferentes dependendo do tipo de feição que existe nos dados, podendo ser pontos, linhas ou polígonos. Como vimos anteriormente, <strong>mundo</strong> tem um objeto do tipo <strong>sf</strong> e, por isso, vamos usar <strong>geom_sf</strong> para sua representação gráfica. Veja que a primeira linha chama a função <strong>ggplot</strong> . No final da primeira linha tem um sinal <strong>+</strong> indicando que outros elementos serão adicionados. Todas as linhas que serão adicionadas nesta função ficarão com recuo de 2 caracteres em relação à primeira linha. (Figura <a href="quali1.html#fig:plot-mundo">6.2</a>).</p>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb217-1"><a href="quali1.html#cb217-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> mundo) <span class="sc">+</span></span>
<span id="cb217-2"><a href="quali1.html#cb217-2" tabindex="-1"></a>  <span class="fu">geom_sf</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:plot-mundo"></span>
<img src="bookdownproj_files/figure-html/plot-mundo-1.png" alt="Mapa base" width="672" />
<p class="caption">
Figure 6.2: Mapa base
</p>
</div>
<p>Observe que não é necessário colocar <strong>data =</strong> quando for indicar que quer visualizar o objeto ‘mundo’. Esta indicação pode ser feita de forma direta <em>ggplot(mundo)</em>.</p>
<p>Podemos alterar as cores do contorno dos países e do seu preenchimento adicionando as novas cores com os atributos ‘color’(ou ‘colour’) para o contorno e ‘fill’ para o preenchimento. Vamos usar tonalidades diferentes de cinza para estes atributos (Figura <a href="quali1.html#fig:plot-mundo-grey">6.3</a>). Entenda melhor como funcionam as cores no <strong>R</strong> consultando <a href="https://r-charts.com/colors/" class="uri">https://r-charts.com/colors/</a>.</p>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb218-1"><a href="quali1.html#cb218-1" tabindex="-1"></a><span class="fu">ggplot</span>(mundo) <span class="sc">+</span> </span>
<span id="cb218-2"><a href="quali1.html#cb218-2" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">color =</span> <span class="st">&quot;grey80&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;grey90&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:plot-mundo-grey"></span>
<img src="bookdownproj_files/figure-html/plot-mundo-grey-1.png" alt="Mapa base em cinza claro" width="672" />
<p class="caption">
Figure 6.3: Mapa base em cinza claro
</p>
</div>
<p>Agora vamos adicionar a segunda camada do mapa, a camada ‘biomaswgs84’. Para isso, precisamos indicar o nome da camada e qual o campo (variável) que definirá o preenchimento (neste caso, o campo <strong>name_biome</strong>), que contém os nomes de cada um dos biomas, um dado qualitativo nominal. O arranjo estético é dado por <strong>aes()</strong>, que descreve a propriedade visual da geometria (geom). Então na nova camada <strong>geom_sf</strong> precisamos indicar qual o banco de dados (<strong>biomaswgs84</strong>) e que queremos que o campo <strong>name_biome</strong> seja preenchido com cores (<em>fill</em>) (Figura <a href="quali1.html#fig:plot-mundo-biomas">6.4</a>).</p>
<div class="sourceCode" id="cb219"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb219-1"><a href="quali1.html#cb219-1" tabindex="-1"></a><span class="fu">ggplot</span>(mundo) <span class="sc">+</span> </span>
<span id="cb219-2"><a href="quali1.html#cb219-2" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">color =</span> <span class="st">&quot;grey80&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;grey90&quot;</span>)<span class="sc">+</span></span>
<span id="cb219-3"><a href="quali1.html#cb219-3" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> biomaswgs84, <span class="fu">aes</span>(<span class="at">fill =</span> name_biome))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:plot-mundo-biomas"></span>
<img src="bookdownproj_files/figure-html/plot-mundo-biomas-1.png" alt="Mapa base em cinza claro e camada de biomas" width="672" />
<p class="caption">
Figure 6.4: Mapa base em cinza claro e camada de biomas
</p>
</div>
<p>O resultado mostra que as duas camadas estão sobrepostas de forma correta e que as cores preenchidas correspondem a uma escala de cor <em>default</em> do <strong>ggplot2</strong>. Além disso, estamos vendo a representação do mundo todo. Como a nossa intenção é obter o mapa de biomas no território brasileiro, precisamos fazer um recorte indicando os limites geográficos que nos interessam. Assim, usando a função <strong>coord_sf</strong> (coordenadas de uma camada <em>simple feature</em> ) vamos indicar as coordenadas limites para o eixo <strong>x</strong> (longitude) e para o eixo <strong>y</strong> (latitude). Conferindo os limites da camada <strong>biomaswgs84</strong> (xmin: -73.98304 ymin: -33.75115 xmax: -28.84785 ymax: 5.269581), vamos aumentar um pouco esta área para termos espaço na área dentro da moldura do mapa. A informação dos limites de uma camada pode ser extraída de <strong>sf::st_crs(biomaswgs84)</strong> ou <strong>head(biomaswgs84)</strong> (Figura <a href="quali1.html#fig:plot-mundo-biomas-recorte">6.5</a>).</p>
<div class="sourceCode" id="cb220"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb220-1"><a href="quali1.html#cb220-1" tabindex="-1"></a><span class="fu">ggplot</span>(mundo) <span class="sc">+</span> </span>
<span id="cb220-2"><a href="quali1.html#cb220-2" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">color =</span> <span class="st">&quot;grey80&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;grey90&quot;</span>)<span class="sc">+</span></span>
<span id="cb220-3"><a href="quali1.html#cb220-3" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data=</span>biomaswgs84, <span class="fu">aes</span>(<span class="at">fill =</span> name_biome)) <span class="sc">+</span></span>
<span id="cb220-4"><a href="quali1.html#cb220-4" tabindex="-1"></a>  <span class="fu">coord_sf</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">77</span>, <span class="sc">-</span><span class="dv">19</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">36</span>, <span class="dv">10</span>), <span class="at">expand =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:plot-mundo-biomas-recorte"></span>
<img src="bookdownproj_files/figure-html/plot-mundo-biomas-recorte-1.png" alt="Mapa base ajustada à camada de biomas" width="672" />
<p class="caption">
Figure 6.5: Mapa base ajustada à camada de biomas
</p>
</div>
<p>A escala de cores não é apropriada para os dados que estão sendo representados. Podemos observar uma ordem na sequência das cores e a utilização de cores inadequadas para algumas feições como para os biomas Amazônia e Sistema Costeiro. Em mapas corocromáticos nominais, as cores devem permitir a diferenciação entre as feições. No <strong>R</strong>, existem diferentes formas de se referir aos nomes das cores e muitas escalas de cores. Com base na tabela em <a href="https://r-charts.com/colors/" class="uri">https://r-charts.com/colors/</a>, você pode escolher os nomes das cores para cada bioma. Para tal, vamos usar a função <strong>scale_fill_manual</strong> e dizer qual cor a partir da ordem em que apareceram na legenda da figura anterior: Amazônia, Caatinga, Cerrado, Mata Atlântica, Pampa, Pantanal e Sistema Costeiro (Figura <a href="quali1.html#fig:plot-mundo-biomas-cores">6.6</a>).</p>
<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb221-1"><a href="quali1.html#cb221-1" tabindex="-1"></a><span class="fu">ggplot</span>(mundo) <span class="sc">+</span> </span>
<span id="cb221-2"><a href="quali1.html#cb221-2" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">color =</span> <span class="st">&quot;grey80&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;grey90&quot;</span>)<span class="sc">+</span></span>
<span id="cb221-3"><a href="quali1.html#cb221-3" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data=</span>biomaswgs84, <span class="fu">aes</span>(<span class="at">fill =</span> name_biome)) <span class="sc">+</span></span>
<span id="cb221-4"><a href="quali1.html#cb221-4" tabindex="-1"></a>  <span class="fu">coord_sf</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">77</span>, <span class="sc">-</span><span class="dv">19</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">36</span>, <span class="dv">10</span>), <span class="at">expand =</span> <span class="cn">FALSE</span>)<span class="sc">+</span></span>
<span id="cb221-5"><a href="quali1.html#cb221-5" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values=</span><span class="fu">c</span>(<span class="st">&quot;forestgreen&quot;</span>, <span class="st">&quot;lightgoldenrodyellow&quot;</span>, <span class="st">&quot;orange1&quot;</span>,<span class="st">&quot;green3&quot;</span>,<span class="st">&quot;indianred&quot;</span>,<span class="st">&quot;mediumorchid3&quot;</span>,<span class="st">&quot;skyblue1&quot;</span>))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:plot-mundo-biomas-cores"></span>
<img src="bookdownproj_files/figure-html/plot-mundo-biomas-cores-1.png" alt="Mapa base e biomas com cores adequadas" width="672" />
<p class="caption">
Figure 6.6: Mapa base e biomas com cores adequadas
</p>
</div>
<p>Agora que as cores foram ajustadas, vamos mudar o título que fica acima da legenda. Para isso, vamos usar a função <strong>labs</strong> (rótulo) dizendo que quer preencher com a palavra “Biomas”(Figura <a href="quali1.html#fig:plot-mundo-biomas-leg">6.7</a>).</p>
<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb222-1"><a href="quali1.html#cb222-1" tabindex="-1"></a><span class="fu">ggplot</span>(mundo) <span class="sc">+</span> </span>
<span id="cb222-2"><a href="quali1.html#cb222-2" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">color =</span> <span class="st">&quot;grey80&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;grey90&quot;</span>)<span class="sc">+</span></span>
<span id="cb222-3"><a href="quali1.html#cb222-3" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> biomaswgs84, <span class="fu">aes</span>(<span class="at">fill =</span> name_biome)) <span class="sc">+</span></span>
<span id="cb222-4"><a href="quali1.html#cb222-4" tabindex="-1"></a>  <span class="fu">coord_sf</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">77</span>, <span class="sc">-</span><span class="dv">19</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">36</span>, <span class="dv">10</span>), <span class="at">expand =</span> <span class="cn">FALSE</span>)<span class="sc">+</span></span>
<span id="cb222-5"><a href="quali1.html#cb222-5" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values=</span><span class="fu">c</span>(<span class="st">&quot;forestgreen&quot;</span>, <span class="st">&quot;lightgoldenrodyellow&quot;</span>, <span class="st">&quot;orange1&quot;</span>,<span class="st">&quot;green3&quot;</span>,<span class="st">&quot;indianred&quot;</span>,<span class="st">&quot;mediumorchid3&quot;</span>,<span class="st">&quot;skyblue1&quot;</span>))<span class="sc">+</span></span>
<span id="cb222-6"><a href="quali1.html#cb222-6" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">fill =</span> <span class="st">&quot;Biomas&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:plot-mundo-biomas-leg"></span>
<img src="bookdownproj_files/figure-html/plot-mundo-biomas-leg-1.png" alt="Título da legenda" width="672" />
<p class="caption">
Figure 6.7: Título da legenda
</p>
</div>
<p>Nem todo mapa precisa de um título no próprio mapa. Ele pode estar na legenda da figura. Este detalhe depende do propósito do mapa. Aqui, vamos colocá-lo na área de fora, acima da área da moldura do mapa. O título do mapa é dado pela função <strong>ggtitle</strong>. O título vai entre aspas (Figura <a href="quali1.html#fig:plot-mundo-biomas-title">6.8</a>).</p>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb223-1"><a href="quali1.html#cb223-1" tabindex="-1"></a><span class="fu">ggplot</span>(mundo) <span class="sc">+</span> </span>
<span id="cb223-2"><a href="quali1.html#cb223-2" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">color =</span> <span class="st">&quot;grey80&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;grey90&quot;</span>)<span class="sc">+</span></span>
<span id="cb223-3"><a href="quali1.html#cb223-3" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data=</span>biomaswgs84, <span class="fu">aes</span>(<span class="at">fill =</span> name_biome)) <span class="sc">+</span></span>
<span id="cb223-4"><a href="quali1.html#cb223-4" tabindex="-1"></a>  <span class="fu">coord_sf</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">77</span>, <span class="sc">-</span><span class="dv">19</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">36</span>, <span class="dv">10</span>), <span class="at">expand =</span> <span class="cn">FALSE</span>)<span class="sc">+</span></span>
<span id="cb223-5"><a href="quali1.html#cb223-5" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values=</span><span class="fu">c</span>(<span class="st">&quot;forestgreen&quot;</span>, <span class="st">&quot;lightgoldenrodyellow&quot;</span>, <span class="st">&quot;orange1&quot;</span>,<span class="st">&quot;green3&quot;</span>,<span class="st">&quot;indianred&quot;</span>,<span class="st">&quot;mediumorchid3&quot;</span>,<span class="st">&quot;skyblue1&quot;</span>))<span class="sc">+</span></span>
<span id="cb223-6"><a href="quali1.html#cb223-6" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">fill =</span> <span class="st">&quot;Biomas&quot;</span>)<span class="sc">+</span></span>
<span id="cb223-7"><a href="quali1.html#cb223-7" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Mapa corocromático nominal: Biomas do Brasil&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:plot-mundo-biomas-title"></span>
<img src="bookdownproj_files/figure-html/plot-mundo-biomas-title-1.png" alt="Título do mapa" width="672" />
<p class="caption">
Figure 6.8: Título do mapa
</p>
</div>
<p><strong>Uma observação importante</strong>: caso quando você acrescente o título usando acentuação como em “corocromático”, apareça um erro, você precisará ajustar a língua para português usando a função <strong>Sys.setlocale(category = “LC_ALL”, locale = “pt_BR.UTF-8”)</strong>.</p>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb224-1"><a href="quali1.html#cb224-1" tabindex="-1"></a><span class="fu">Sys.setlocale</span>(<span class="at">category =</span> <span class="st">&quot;LC_ALL&quot;</span>, <span class="at">locale =</span> <span class="st">&quot;pt_BR.UTF-8&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;LC_COLLATE=pt_BR.UTF-8;LC_CTYPE=pt_BR.UTF-8;LC_MONETARY=pt_BR.UTF-8;LC_NUMERIC=C;LC_TIME=pt_BR.UTF-8&quot;</code></pre>
<p>Rodando o código novamente depois desta função deverá resolver o problema.</p>
<p>Agora vamos alterar a cor do fundo do mapa usando a função <strong>theme()</strong>, indicando que a cor do fundo deve ser “aliceblue” (Figura <a href="quali1.html#fig:plot-fundo">6.9</a>).</p>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb226-1"><a href="quali1.html#cb226-1" tabindex="-1"></a><span class="fu">ggplot</span>(mundo) <span class="sc">+</span> </span>
<span id="cb226-2"><a href="quali1.html#cb226-2" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">color =</span> <span class="st">&quot;grey80&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;grey90&quot;</span>)<span class="sc">+</span></span>
<span id="cb226-3"><a href="quali1.html#cb226-3" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data=</span>biomaswgs84, <span class="fu">aes</span>(<span class="at">fill =</span> name_biome)) <span class="sc">+</span></span>
<span id="cb226-4"><a href="quali1.html#cb226-4" tabindex="-1"></a>  <span class="fu">coord_sf</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">77</span>, <span class="sc">-</span><span class="dv">19</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">36</span>, <span class="dv">10</span>), <span class="at">expand =</span> <span class="cn">FALSE</span>)<span class="sc">+</span></span>
<span id="cb226-5"><a href="quali1.html#cb226-5" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values=</span><span class="fu">c</span>(<span class="st">&quot;forestgreen&quot;</span>, <span class="st">&quot;lightgoldenrodyellow&quot;</span>, <span class="st">&quot;orange1&quot;</span>,<span class="st">&quot;green3&quot;</span>,<span class="st">&quot;indianred&quot;</span>,<span class="st">&quot;mediumorchid3&quot;</span>,<span class="st">&quot;skyblue1&quot;</span>))<span class="sc">+</span></span>
<span id="cb226-6"><a href="quali1.html#cb226-6" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">fill =</span> <span class="st">&quot;Biomas&quot;</span>)<span class="sc">+</span></span>
<span id="cb226-7"><a href="quali1.html#cb226-7" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Mapa corocromático nominal: Biomas do Brasil&quot;</span>) <span class="sc">+</span></span>
<span id="cb226-8"><a href="quali1.html#cb226-8" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">&quot;aliceblue&quot;</span>))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:plot-fundo"></span>
<img src="bookdownproj_files/figure-html/plot-fundo-1.png" alt="Mapa com fundo azul claro" width="672" />
<p class="caption">
Figure 6.9: Mapa com fundo azul claro
</p>
</div>
<p>Nós podemos optar por deixar a legenda fora da moldura do mapa, como já está. No entanto, é importante saber como posicioná-la na parte de dentro.
Para ajustar os elementos dentro da moldura, considere que o canto inferior esquerdo é a posição (0,0) e o canto superior direito, a posição (1,1). Por padrão, se não ajustarmos <em>justification</em>, a legenda ficará centralizada a partir da posição que definirmos na posição da legenda, o que cortará parte da mesma.
Teste cada uma das quatro posiçoes a partir dos cantos, com a respectiva <em>justification</em>, alternando entre (0,0), (0,1), (1,0) e (1,1). Vamos ficar com a posição c(1, 0.2).
A Figura <a href="quali1.html#fig:posicao-01">6.10</a> mostra como é a posição da legenda em (0,1).</p>
<div class="sourceCode" id="cb227"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb227-1"><a href="quali1.html#cb227-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> mundo) <span class="sc">+</span> </span>
<span id="cb227-2"><a href="quali1.html#cb227-2" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">color =</span> <span class="st">&quot;grey80&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;grey90&quot;</span>)<span class="sc">+</span></span>
<span id="cb227-3"><a href="quali1.html#cb227-3" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> biomaswgs84, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">fill =</span> name_biome)) <span class="sc">+</span></span>
<span id="cb227-4"><a href="quali1.html#cb227-4" tabindex="-1"></a>  <span class="fu">coord_sf</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">77</span>, <span class="sc">-</span><span class="dv">19</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">36</span>, <span class="dv">10</span>), <span class="at">expand =</span> <span class="cn">FALSE</span>)<span class="sc">+</span></span>
<span id="cb227-5"><a href="quali1.html#cb227-5" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values=</span><span class="fu">c</span>(<span class="st">&quot;forestgreen&quot;</span>, <span class="st">&quot;lightgoldenrodyellow&quot;</span>, <span class="st">&quot;orange1&quot;</span>,<span class="st">&quot;green3&quot;</span>,<span class="st">&quot;indianred&quot;</span>,<span class="st">&quot;mediumorchid3&quot;</span>,<span class="st">&quot;skyblue1&quot;</span>))<span class="sc">+</span></span>
<span id="cb227-6"><a href="quali1.html#cb227-6" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">fill =</span> <span class="st">&quot;Biomas&quot;</span>)<span class="sc">+</span></span>
<span id="cb227-7"><a href="quali1.html#cb227-7" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Mapa corocromático nominal: Biomas do Brasil&quot;</span>) <span class="sc">+</span></span>
<span id="cb227-8"><a href="quali1.html#cb227-8" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">&quot;aliceblue&quot;</span>))<span class="sc">+</span></span>
<span id="cb227-9"><a href="quali1.html#cb227-9" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), </span>
<span id="cb227-10"><a href="quali1.html#cb227-10" tabindex="-1"></a>       <span class="at">legend.justification =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">0.2</span>), </span>
<span id="cb227-11"><a href="quali1.html#cb227-11" tabindex="-1"></a>       <span class="at">legend.background =</span> <span class="fu">element_rect</span>(<span class="at">colour =</span> <span class="cn">NA</span>, <span class="at">fill =</span> <span class="st">&quot;white&quot;</span>))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:posicao-01"></span>
<img src="bookdownproj_files/figure-html/posicao-01-1.png" alt="Legenda na posição (0,1)" width="672" />
<p class="caption">
Figure 6.10: Legenda na posição (0,1)
</p>
</div>
<p>Vamos precisar diminuir um pouco o tamanho da legenda.
Uma legenda é composta por diversos elementos e todos podem ser ajustados: caixa da legenda, título, texto, espaçamento, cor do fundo, cor da moldura, entre outros. Para saber os ajustes que estão sendo usados use a função <strong>theme_get()</strong>. Segue a função para ajustes de alguns elementos.</p>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb228-1"><a href="quali1.html#cb228-1" tabindex="-1"></a><span class="fu">theme</span>(<span class="at">legend.key.size =</span> <span class="fu">unit</span>(<span class="dv">1</span>, <span class="st">&#39;cm&#39;</span>), <span class="co">#muda o tamanho da caixa da legenda</span></span>
<span id="cb228-2"><a href="quali1.html#cb228-2" tabindex="-1"></a>        <span class="at">legend.key.height =</span> <span class="fu">unit</span>(<span class="dv">1</span>, <span class="st">&#39;cm&#39;</span>), <span class="co">#muda a altura da caixa da legenda</span></span>
<span id="cb228-3"><a href="quali1.html#cb228-3" tabindex="-1"></a>        <span class="at">legend.key.width =</span> <span class="fu">unit</span>(<span class="dv">1</span>, <span class="st">&#39;cm&#39;</span>), <span class="co">#muda a largura da caixa da legenda</span></span>
<span id="cb228-4"><a href="quali1.html#cb228-4" tabindex="-1"></a>        <span class="at">legend.title =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">14</span>), <span class="co">#muda o tamanho da fonte do título</span></span>
<span id="cb228-5"><a href="quali1.html#cb228-5" tabindex="-1"></a>        <span class="at">legend.text =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">10</span>)) <span class="co">#muda o tamanho da fonte do texto</span></span></code></pre></div>
<p>Vamos reduzir o tamanho da fonte do título da legenda e do texto (Figura <a href="quali1.html#fig:plot-text-size">6.11</a>). As possibilidades de edição são inúmeras usando <strong>ggplot2</strong>. Sugiro consultar o site <a href="https://ggplot2.tidyverse.org/index.html" class="uri">https://ggplot2.tidyverse.org/index.html</a> e o livro online <strong>R Graphics Cookbook</strong> (CHANG, 2023), que cobrem todos os detalhes.</p>
<div class="sourceCode" id="cb229"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb229-1"><a href="quali1.html#cb229-1" tabindex="-1"></a><span class="fu">ggplot</span>(mundo) <span class="sc">+</span> </span>
<span id="cb229-2"><a href="quali1.html#cb229-2" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">color =</span> <span class="st">&quot;grey80&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;grey90&quot;</span>)<span class="sc">+</span></span>
<span id="cb229-3"><a href="quali1.html#cb229-3" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data=</span>biomaswgs84, <span class="fu">aes</span>(<span class="at">fill =</span> name_biome)) <span class="sc">+</span></span>
<span id="cb229-4"><a href="quali1.html#cb229-4" tabindex="-1"></a>  <span class="fu">coord_sf</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">77</span>, <span class="sc">-</span><span class="dv">19</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">36</span>, <span class="dv">10</span>), <span class="at">expand =</span> <span class="cn">FALSE</span>)<span class="sc">+</span></span>
<span id="cb229-5"><a href="quali1.html#cb229-5" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values=</span><span class="fu">c</span>(<span class="st">&quot;forestgreen&quot;</span>, <span class="st">&quot;lightgoldenrodyellow&quot;</span>, <span class="st">&quot;orange1&quot;</span>,<span class="st">&quot;green3&quot;</span>,<span class="st">&quot;indianred&quot;</span>,<span class="st">&quot;mediumorchid3&quot;</span>,<span class="st">&quot;skyblue1&quot;</span>))<span class="sc">+</span></span>
<span id="cb229-6"><a href="quali1.html#cb229-6" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">fill =</span> <span class="st">&quot;Biomas&quot;</span>)<span class="sc">+</span></span>
<span id="cb229-7"><a href="quali1.html#cb229-7" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Mapa corocromático nominal: Biomas do Brasil&quot;</span>) <span class="sc">+</span></span>
<span id="cb229-8"><a href="quali1.html#cb229-8" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">&quot;aliceblue&quot;</span>))<span class="sc">+</span></span>
<span id="cb229-9"><a href="quali1.html#cb229-9" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>), </span>
<span id="cb229-10"><a href="quali1.html#cb229-10" tabindex="-1"></a>       <span class="at">legend.justification =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>), </span>
<span id="cb229-11"><a href="quali1.html#cb229-11" tabindex="-1"></a>       <span class="at">legend.background =</span> <span class="fu">element_rect</span>(<span class="at">colour =</span> <span class="cn">NA</span>, <span class="at">fill =</span> <span class="st">&quot;white&quot;</span>),</span>
<span id="cb229-12"><a href="quali1.html#cb229-12" tabindex="-1"></a>       <span class="at">legend.title =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">8</span>),</span>
<span id="cb229-13"><a href="quali1.html#cb229-13" tabindex="-1"></a>       <span class="at">legend.text =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">7</span>))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:plot-text-size"></span>
<img src="bookdownproj_files/figure-html/plot-text-size-1.png" alt="Redução das fontes do título da legenda e texto" width="672" />
<p class="caption">
Figure 6.11: Redução das fontes do título da legenda e texto
</p>
</div>
<p>O título pode ser colocado dentro da área do mapa, do lado direito. Vamos acrescentar esta informação logo abaixo da definição do título no código, usando <strong>theme(plot.title = element_text(hjust = 1, vjust = -8))</strong> para que o alinhamento fique à direita (hjust = 1) e que fique dentro da área (vjust = -8) (Figura <a href="quali1.html#fig:plot-alin-title">6.12</a>).</p>
<div class="sourceCode" id="cb230"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb230-1"><a href="quali1.html#cb230-1" tabindex="-1"></a><span class="fu">ggplot</span>(mundo) <span class="sc">+</span> </span>
<span id="cb230-2"><a href="quali1.html#cb230-2" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">color =</span> <span class="st">&quot;grey80&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;grey90&quot;</span>)<span class="sc">+</span></span>
<span id="cb230-3"><a href="quali1.html#cb230-3" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data=</span>biomaswgs84, <span class="fu">aes</span>(<span class="at">fill =</span> name_biome)) <span class="sc">+</span></span>
<span id="cb230-4"><a href="quali1.html#cb230-4" tabindex="-1"></a>  <span class="fu">coord_sf</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">77</span>, <span class="sc">-</span><span class="dv">19</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">36</span>, <span class="dv">10</span>), <span class="at">expand =</span> <span class="cn">FALSE</span>)<span class="sc">+</span></span>
<span id="cb230-5"><a href="quali1.html#cb230-5" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values=</span><span class="fu">c</span>(<span class="st">&quot;forestgreen&quot;</span>, <span class="st">&quot;lightgoldenrodyellow&quot;</span>, <span class="st">&quot;orange1&quot;</span>,<span class="st">&quot;green3&quot;</span>,<span class="st">&quot;indianred&quot;</span>,<span class="st">&quot;mediumorchid3&quot;</span>,<span class="st">&quot;skyblue1&quot;</span>))<span class="sc">+</span></span>
<span id="cb230-6"><a href="quali1.html#cb230-6" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">fill =</span> <span class="st">&quot;Biomas&quot;</span>)<span class="sc">+</span></span>
<span id="cb230-7"><a href="quali1.html#cb230-7" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Mapa corocromático nominal: Biomas do Brasil&quot;</span>) <span class="sc">+</span></span>
<span id="cb230-8"><a href="quali1.html#cb230-8" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">&quot;aliceblue&quot;</span>))<span class="sc">+</span></span>
<span id="cb230-9"><a href="quali1.html#cb230-9" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="dv">1</span>, <span class="at">vjust =</span> <span class="sc">-</span><span class="dv">8</span>))<span class="sc">+</span></span>
<span id="cb230-10"><a href="quali1.html#cb230-10" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>), </span>
<span id="cb230-11"><a href="quali1.html#cb230-11" tabindex="-1"></a>       <span class="at">legend.justification =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>), </span>
<span id="cb230-12"><a href="quali1.html#cb230-12" tabindex="-1"></a>       <span class="at">legend.background =</span> <span class="fu">element_rect</span>(<span class="at">colour =</span> <span class="cn">NA</span>, <span class="at">fill =</span> <span class="st">&quot;white&quot;</span>),</span>
<span id="cb230-13"><a href="quali1.html#cb230-13" tabindex="-1"></a>       <span class="at">legend.title =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">9</span>),</span>
<span id="cb230-14"><a href="quali1.html#cb230-14" tabindex="-1"></a>       <span class="at">legend.text =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">8</span>))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:plot-alin-title"></span>
<img src="bookdownproj_files/figure-html/plot-alin-title-1.png" alt="Alinhamento do título" width="672" />
<p class="caption">
Figure 6.12: Alinhamento do título
</p>
</div>
<p>Precisamos adicionar um elemento muito importante: a escala gráfica!
A função <strong>ggspatial::annotation_scale(location = “br”, width_hint = 0.4, line_width = 0.5, height = unit(0.1,“cm”))</strong> indica que a localização da escala gráfica será “br”, ou seja, <em>bottom right</em> (inferior direito). <strong>width_hint</strong> é a largura total da barra da escala. A espessura da linha da barra da escala é dada por <strong>line_width</strong> e <strong>height</strong>, a altura.
Vamos aproveitar também para colocar uma linha de contorno na moldura do mapa. Essa linha é a <strong>panel.border</strong>.
As linhas do Equador e do Trópico de Capricórnio podem ser adicionadas com a função <strong>geo_hline()</strong> ajustando os valores para 0 (Equador) e -23.27 para o Trópico. O tipo da linha será pontilhado “dashed”.
Também podemos deixar sem linhas dos contornos dos biomas usando <strong>colour=NA</strong> na camada “biomaswgs84” (Figura <a href="quali1.html#fig:plot-escala">6.13</a>).</p>
<div class="sourceCode" id="cb231"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb231-1"><a href="quali1.html#cb231-1" tabindex="-1"></a><span class="fu">ggplot</span>(mundo) <span class="sc">+</span> </span>
<span id="cb231-2"><a href="quali1.html#cb231-2" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">color =</span> <span class="st">&quot;grey80&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;grey90&quot;</span>)<span class="sc">+</span></span>
<span id="cb231-3"><a href="quali1.html#cb231-3" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> biomaswgs84, <span class="fu">aes</span>(<span class="at">fill =</span> name_biome), <span class="at">colour=</span><span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb231-4"><a href="quali1.html#cb231-4" tabindex="-1"></a>  <span class="fu">coord_sf</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">77</span>, <span class="sc">-</span><span class="dv">19</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">36</span>, <span class="dv">10</span>), <span class="at">expand =</span> <span class="cn">FALSE</span>)<span class="sc">+</span></span>
<span id="cb231-5"><a href="quali1.html#cb231-5" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>)<span class="sc">+</span></span>
<span id="cb231-6"><a href="quali1.html#cb231-6" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span><span class="sc">-</span><span class="fl">23.27</span>, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>)<span class="sc">+</span></span>
<span id="cb231-7"><a href="quali1.html#cb231-7" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values=</span><span class="fu">c</span>(<span class="st">&quot;forestgreen&quot;</span>, <span class="st">&quot;lightgoldenrodyellow&quot;</span>, <span class="st">&quot;orange1&quot;</span>,<span class="st">&quot;green3&quot;</span>,<span class="st">&quot;indianred&quot;</span>,<span class="st">&quot;mediumorchid3&quot;</span>,<span class="st">&quot;skyblue1&quot;</span>))<span class="sc">+</span></span>
<span id="cb231-8"><a href="quali1.html#cb231-8" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">fill =</span> <span class="st">&quot;Biomas&quot;</span>)<span class="sc">+</span></span>
<span id="cb231-9"><a href="quali1.html#cb231-9" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Mapa corocromático nominal: Biomas do Brasil&quot;</span>) <span class="sc">+</span></span>
<span id="cb231-10"><a href="quali1.html#cb231-10" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">&quot;aliceblue&quot;</span>))<span class="sc">+</span></span>
<span id="cb231-11"><a href="quali1.html#cb231-11" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="dv">1</span>, <span class="at">vjust =</span> <span class="sc">-</span><span class="dv">8</span>))<span class="sc">+</span></span>
<span id="cb231-12"><a href="quali1.html#cb231-12" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">0.2</span>), </span>
<span id="cb231-13"><a href="quali1.html#cb231-13" tabindex="-1"></a>       <span class="at">legend.justification =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">0.2</span>), </span>
<span id="cb231-14"><a href="quali1.html#cb231-14" tabindex="-1"></a>       <span class="at">legend.background =</span> <span class="fu">element_rect</span>(<span class="at">colour =</span> <span class="cn">NA</span>, <span class="at">fill =</span> <span class="st">&quot;white&quot;</span>),</span>
<span id="cb231-15"><a href="quali1.html#cb231-15" tabindex="-1"></a>       <span class="at">legend.title =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">9</span>),</span>
<span id="cb231-16"><a href="quali1.html#cb231-16" tabindex="-1"></a>       <span class="at">legend.text =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">8</span>),</span>
<span id="cb231-17"><a href="quali1.html#cb231-17" tabindex="-1"></a>       <span class="at">panel.border =</span> <span class="fu">element_rect</span>(<span class="at">color =</span> <span class="st">&quot;black&quot;</span>,<span class="at">size =</span> .<span class="dv">1</span>,<span class="at">fill =</span> <span class="cn">NA</span>))<span class="sc">+</span></span>
<span id="cb231-18"><a href="quali1.html#cb231-18" tabindex="-1"></a>  ggspatial<span class="sc">::</span><span class="fu">annotation_scale</span>(<span class="at">location =</span> <span class="st">&quot;br&quot;</span>, <span class="at">width_hint =</span> <span class="fl">0.3</span>, <span class="at">line_width =</span> <span class="fl">0.5</span>, <span class="at">height =</span> <span class="fu">unit</span>(<span class="fl">0.1</span>,<span class="st">&quot;cm&quot;</span>))</span></code></pre></div>
<pre><code>## Warning: The `size` argument of `element_rect()` is deprecated as of ggplot2
## 3.4.0.
## ℹ Please use the `linewidth` argument instead.
## This warning is displayed once every 8 hours.
## Call `lifecycle::last_lifecycle_warnings()` to see where this warning
## was generated.</code></pre>
<pre><code>## Scale on map varies by more than 10%, scale bar may be inaccurate</code></pre>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:plot-escala"></span>
<img src="bookdownproj_files/figure-html/plot-escala-1.png" alt="Escala gráfica, Equador e Trópico de Capricórnio" width="672" />
<p class="caption">
Figure 6.13: Escala gráfica, Equador e Trópico de Capricórnio
</p>
</div>
<p>Observe que quando inserimos as linhas do Equador e do Trópico de Capricórnio, apareceu o título no eixo y como “yintercept”. Para remover esta informação, basta indicar que o título do eixo não deve ter preenchimento <strong>axis.title.y = element_blank())</strong>.
Embora o mapa de biomas pareça satisfatório, não temos referências internas da localização dos biomas. Seria interessante adicionar a camada dos estados (Unidades da Federação = UF) sem preenchimento e com o contorno em cinza médio (grey50). Para isso, primeiro vamos criar uma camada “sf” usando uma função do <strong>geobr</strong>, que é a “read_state”.</p>
<div class="sourceCode" id="cb234"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb234-1"><a href="quali1.html#cb234-1" tabindex="-1"></a>uf <span class="ot">&lt;-</span> <span class="fu">read_state</span>(<span class="at">code_state =</span> <span class="st">&quot;all&quot;</span>, <span class="at">year =</span> <span class="dv">2010</span>, <span class="at">simplified =</span> <span class="cn">TRUE</span>, <span class="at">showProgress =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## Using year 2010</code></pre>
<p>Em seguida, vamos transformar a projeção da camada “uf” para que fique em WGS84.</p>
<div class="sourceCode" id="cb236"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb236-1"><a href="quali1.html#cb236-1" tabindex="-1"></a>ufwgs84 <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(uf, <span class="st">&quot;+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0&quot;</span>)</span></code></pre></div>
<p>Agora adicionamos a camada <strong>ufwgs84</strong> logo abaixo da linha de código da camada <strong>biomaswgs84</strong>. O atributo <strong>alpha = 0</strong> indica que não deve haver preenchimento da camada, ou seja, ela deverá ficar transparente e o contorno deverá ser “grey50” (Figura <a href="quali1.html#fig:plot-uf">6.14</a>).</p>
<div class="sourceCode" id="cb237"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb237-1"><a href="quali1.html#cb237-1" tabindex="-1"></a><span class="fu">ggplot</span>(mundo) <span class="sc">+</span> </span>
<span id="cb237-2"><a href="quali1.html#cb237-2" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">color =</span> <span class="st">&quot;grey80&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;grey90&quot;</span>)<span class="sc">+</span></span>
<span id="cb237-3"><a href="quali1.html#cb237-3" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> biomaswgs84, <span class="fu">aes</span>(<span class="at">fill =</span> name_biome), <span class="at">colour=</span><span class="cn">NA</span>)<span class="sc">+</span></span>
<span id="cb237-4"><a href="quali1.html#cb237-4" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> ufwgs84, <span class="at">colour =</span> <span class="st">&quot;grey50&quot;</span>, <span class="at">alpha =</span> <span class="dv">0</span>)<span class="sc">+</span></span>
<span id="cb237-5"><a href="quali1.html#cb237-5" tabindex="-1"></a>  <span class="fu">coord_sf</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">77</span>, <span class="sc">-</span><span class="dv">19</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">36</span>, <span class="dv">10</span>), <span class="at">expand =</span> <span class="cn">FALSE</span>)<span class="sc">+</span></span>
<span id="cb237-6"><a href="quali1.html#cb237-6" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>)<span class="sc">+</span></span>
<span id="cb237-7"><a href="quali1.html#cb237-7" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span><span class="sc">-</span><span class="fl">23.27</span>, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>)<span class="sc">+</span></span>
<span id="cb237-8"><a href="quali1.html#cb237-8" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values=</span><span class="fu">c</span>(<span class="st">&quot;forestgreen&quot;</span>, <span class="st">&quot;lightgoldenrodyellow&quot;</span>, <span class="st">&quot;orange1&quot;</span>,<span class="st">&quot;green3&quot;</span>,<span class="st">&quot;indianred&quot;</span>,<span class="st">&quot;mediumorchid3&quot;</span>,<span class="st">&quot;skyblue1&quot;</span>))<span class="sc">+</span></span>
<span id="cb237-9"><a href="quali1.html#cb237-9" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">fill =</span> <span class="st">&quot;Biomas&quot;</span>)<span class="sc">+</span></span>
<span id="cb237-10"><a href="quali1.html#cb237-10" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Mapa corocromático nominal: Biomas do Brasil&quot;</span>) <span class="sc">+</span></span>
<span id="cb237-11"><a href="quali1.html#cb237-11" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">&quot;aliceblue&quot;</span>))<span class="sc">+</span></span>
<span id="cb237-12"><a href="quali1.html#cb237-12" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="dv">1</span>, <span class="at">vjust =</span> <span class="sc">-</span><span class="dv">8</span>))<span class="sc">+</span></span>
<span id="cb237-13"><a href="quali1.html#cb237-13" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">0.2</span>), </span>
<span id="cb237-14"><a href="quali1.html#cb237-14" tabindex="-1"></a>       <span class="at">legend.justification =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">0.2</span>), </span>
<span id="cb237-15"><a href="quali1.html#cb237-15" tabindex="-1"></a>       <span class="at">legend.background =</span> <span class="fu">element_rect</span>(<span class="at">colour =</span> <span class="cn">NA</span>, <span class="at">fill =</span> <span class="st">&quot;white&quot;</span>),</span>
<span id="cb237-16"><a href="quali1.html#cb237-16" tabindex="-1"></a>       <span class="at">legend.title =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">9</span>),</span>
<span id="cb237-17"><a href="quali1.html#cb237-17" tabindex="-1"></a>       <span class="at">legend.text =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">8</span>),</span>
<span id="cb237-18"><a href="quali1.html#cb237-18" tabindex="-1"></a>       <span class="at">panel.border =</span> <span class="fu">element_rect</span>(<span class="at">color =</span> <span class="st">&quot;black&quot;</span>,<span class="at">size =</span> .<span class="dv">1</span>,<span class="at">fill =</span> <span class="cn">NA</span>),</span>
<span id="cb237-19"><a href="quali1.html#cb237-19" tabindex="-1"></a>       <span class="at">axis.title.y =</span> <span class="fu">element_blank</span>())<span class="sc">+</span></span>
<span id="cb237-20"><a href="quali1.html#cb237-20" tabindex="-1"></a>  ggspatial<span class="sc">::</span><span class="fu">annotation_scale</span>(<span class="at">location =</span> <span class="st">&quot;br&quot;</span>, <span class="at">width_hint =</span> <span class="fl">0.4</span>, <span class="at">line_width =</span> <span class="fl">0.5</span>, <span class="at">height =</span> <span class="fu">unit</span>(<span class="fl">0.1</span>,<span class="st">&quot;cm&quot;</span>))</span></code></pre></div>
<pre><code>## Scale on map varies by more than 10%, scale bar may be inaccurate</code></pre>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:plot-uf"></span>
<img src="bookdownproj_files/figure-html/plot-uf-1.png" alt="Adicionando os limites das Unidades da Federação" width="672" />
<p class="caption">
Figure 6.14: Adicionando os limites das Unidades da Federação
</p>
</div>
<p>Por último, vamos adicionar a fonte dos dados. Esta informação entra como “caption” na função <strong>labs</strong> e poderá entrar nos parênteses já existentes para <strong>labs</strong> (Figura <a href="quali1.html#fig:plot-caption">6.15</a>).</p>
<div class="sourceCode" id="cb239"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb239-1"><a href="quali1.html#cb239-1" tabindex="-1"></a><span class="fu">ggplot</span>(mundo) <span class="sc">+</span> </span>
<span id="cb239-2"><a href="quali1.html#cb239-2" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">color =</span> <span class="st">&quot;grey80&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;grey90&quot;</span>)<span class="sc">+</span></span>
<span id="cb239-3"><a href="quali1.html#cb239-3" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> biomaswgs84, <span class="fu">aes</span>(<span class="at">fill =</span> name_biome), <span class="at">colour=</span><span class="cn">NA</span>)<span class="sc">+</span></span>
<span id="cb239-4"><a href="quali1.html#cb239-4" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> ufwgs84, <span class="at">colour =</span> <span class="st">&quot;grey50&quot;</span>, <span class="at">alpha =</span> <span class="dv">0</span>)<span class="sc">+</span></span>
<span id="cb239-5"><a href="quali1.html#cb239-5" tabindex="-1"></a>  <span class="fu">coord_sf</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">77</span>, <span class="sc">-</span><span class="dv">19</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">36</span>, <span class="dv">10</span>), <span class="at">expand =</span> <span class="cn">FALSE</span>)<span class="sc">+</span></span>
<span id="cb239-6"><a href="quali1.html#cb239-6" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>)<span class="sc">+</span></span>
<span id="cb239-7"><a href="quali1.html#cb239-7" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span><span class="sc">-</span><span class="fl">23.27</span>, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>)<span class="sc">+</span></span>
<span id="cb239-8"><a href="quali1.html#cb239-8" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values=</span><span class="fu">c</span>(<span class="st">&quot;forestgreen&quot;</span>, <span class="st">&quot;lightgoldenrodyellow&quot;</span>, <span class="st">&quot;orange1&quot;</span>,<span class="st">&quot;green3&quot;</span>,<span class="st">&quot;indianred&quot;</span>,<span class="st">&quot;mediumorchid3&quot;</span>,<span class="st">&quot;skyblue1&quot;</span>))<span class="sc">+</span></span>
<span id="cb239-9"><a href="quali1.html#cb239-9" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">fill =</span> <span class="st">&quot;Biomas&quot;</span>,</span>
<span id="cb239-10"><a href="quali1.html#cb239-10" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">&quot;Fonte: IBGE (2019) </span><span class="sc">\n</span><span class="st"> Elaborado por: @Ligiaviz&quot;</span>) <span class="sc">+</span></span>
<span id="cb239-11"><a href="quali1.html#cb239-11" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Mapa corocromático nominal: Biomas do Brasil&quot;</span>) <span class="sc">+</span></span>
<span id="cb239-12"><a href="quali1.html#cb239-12" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">&quot;aliceblue&quot;</span>))<span class="sc">+</span></span>
<span id="cb239-13"><a href="quali1.html#cb239-13" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>, <span class="at">hjust =</span> <span class="dv">1</span>, <span class="at">vjust =</span> <span class="sc">-</span><span class="dv">8</span>))<span class="sc">+</span></span>
<span id="cb239-14"><a href="quali1.html#cb239-14" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">0.2</span>), </span>
<span id="cb239-15"><a href="quali1.html#cb239-15" tabindex="-1"></a>       <span class="at">legend.justification =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">0.2</span>), </span>
<span id="cb239-16"><a href="quali1.html#cb239-16" tabindex="-1"></a>       <span class="at">legend.background =</span> <span class="fu">element_rect</span>(<span class="at">colour =</span> <span class="cn">NA</span>, <span class="at">fill =</span> <span class="st">&quot;white&quot;</span>),</span>
<span id="cb239-17"><a href="quali1.html#cb239-17" tabindex="-1"></a>       <span class="at">legend.title =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">8</span>),</span>
<span id="cb239-18"><a href="quali1.html#cb239-18" tabindex="-1"></a>       <span class="at">legend.text =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">7</span>),</span>
<span id="cb239-19"><a href="quali1.html#cb239-19" tabindex="-1"></a>       <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">7</span>),</span>
<span id="cb239-20"><a href="quali1.html#cb239-20" tabindex="-1"></a>       <span class="at">panel.border =</span> <span class="fu">element_rect</span>(<span class="at">color =</span> <span class="st">&quot;black&quot;</span>,<span class="at">size =</span> .<span class="dv">1</span>,<span class="at">fill =</span> <span class="cn">NA</span>),</span>
<span id="cb239-21"><a href="quali1.html#cb239-21" tabindex="-1"></a>       <span class="at">axis.title.y =</span> <span class="fu">element_blank</span>())<span class="sc">+</span></span>
<span id="cb239-22"><a href="quali1.html#cb239-22" tabindex="-1"></a>  ggspatial<span class="sc">::</span><span class="fu">annotation_scale</span>(<span class="at">location =</span> <span class="st">&quot;br&quot;</span>, <span class="at">width_hint =</span> <span class="fl">0.4</span>, <span class="at">line_width =</span> <span class="fl">0.5</span>, <span class="at">height =</span> <span class="fu">unit</span>(<span class="fl">0.1</span>,<span class="st">&quot;cm&quot;</span>))</span></code></pre></div>
<pre><code>## Scale on map varies by more than 10%, scale bar may be inaccurate</code></pre>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:plot-caption"></span>
<img src="bookdownproj_files/figure-html/plot-caption-1.png" alt="Mapa final com fonte de dados" width="672" />
<p class="caption">
Figure 6.15: Mapa final com fonte de dados
</p>
</div>
<p>Pronto! Nosso primeiro mapa em <strong>R</strong> está finalizado! E nem doeu…
Você pode salvar o arquivo no formato <strong>png</strong>. Ele estará no seu diretório de trabalho.</p>
<div class="sourceCode" id="cb241"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb241-1"><a href="quali1.html#cb241-1" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="st">&quot;biomas.png&quot;</span>, <span class="at">width =</span> <span class="dv">8</span>, <span class="at">height =</span> <span class="dv">8</span>, <span class="at">dpi =</span> <span class="dv">300</span>)</span></code></pre></div>
</div>
<div id="referências-citadas-1" class="section level2 unnumbered hasAnchor">
<h2>Referências citadas<a href="quali1.html#referências-citadas-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>CHANG, W. (2023) <strong>R Graphics Cookbook</strong>: Practical Recipes for Visualizing Data. 2nd Edition. <a href="https://r-graphics.org/index.html" class="uri">https://r-graphics.org/index.html</a></p>
<p>PEBESMA, E. (2018). Simple Features for R: Standardized Support for Spatial Vector Data. <strong>The R Journal</strong> 10:1, 439-446. <a href="https://journal.r-project.org/archive/2018/RJ-2018-009/index.html" class="uri">https://journal.r-project.org/archive/2018/RJ-2018-009/index.html</a></p>
<p>PEREIRA, R.H.M.; GONÇALVES, C.N. (2021) <strong>geobr</strong>: Loads Shapefiles of Official Spatial Data Sets of Brazil. GitHub repository - <a href="https://github.com/ipeaGIT/geobr" class="uri">https://github.com/ipeaGIT/geobr</a>.</p>
<p>WICKHAM, H. (2010) A Layered Grammar of Graphics. <strong>Journal of Computational and Graphical Statistics</strong>, 19(1).</p>
<p>WICKHAM, H. (2016). <strong>ggplot2</strong>: Elegant Graphics for Data Analysis. Springer-Verlag New York. ISBN 978-3-319-24277-4, <a href="https://ggplot2.tidyverse.org" class="uri">https://ggplot2.tidyverse.org</a>.</p>
<p>WILKINSON, L., WILLS, G. (2005) <strong>The Grammar of Graphics</strong>. 2nd Edition. New York: Springer. 690p.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="tipos.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="quali2.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/ligiaviz/RCartoTematica/edit/main/06-coroc-nominal.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/ligiaviz/RCartoTematica/blob/main/06-coroc-nominal.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
